# Default values for product-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

podAnnotations: {}

product_service:
  deployment:
    name:
    replicas: 1
  container:
    name:
  service:
    name:
    port: 9090
    type: LoadBalancer
  image:
    name: truenemec/product-service
    tag: 0.0.3-SNAPSHOT
    pullPolicy: IfNotPresent

product_db:
  db:
    user: product_db
    password: product_db
    dbname: product_db
  deployment:
    name:
    replicas: 1
  container:
    name:
  service:
    name:
    port: 6001
    type: LoadBalancer
  image:
    name: postgres
    tag: 12.4
    pullPolicy: IfNotPresent
