package com.demo.productservice.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@DynamoDBTable(tableName = "message")
@Builder
@AllArgsConstructor
@Getter
@NoArgsConstructor
@Setter
public class MessageItem {

    @DynamoDBHashKey(attributeName="guid")
    @DynamoDBAutoGeneratedKey
    private String guid;

    @DynamoDBAttribute(attributeName = "message")
    private String message;

    @DynamoDBAttribute(attributeName = "severity")
    private String severity;

}
