spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://product-db:5432/product_db}
    username: ${DATABASE_USER:product_db}
    password: ${DATABASE_PASSWORD:product_db}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
amazon:
  aws:
    access-key: fakeMyKeyId
    secret-key: fakeSecretAccessKey
    region: us-west-1
    dynamo-db-endpoint: 'http://localhost:8000'

retry:
  maxAttempts: 3
  maxDelay: 100

mastercard-handler:
  default-path: 'e:\CODE\new-demo\product-service\src\test\resources\sample\mastercard\'

visa-handler:
  default-path: 'e:\CODE\new-demo\product-service\src\test\resources\sample\visa\'

visa-map-config:
  header-column-number: 1
  column-map:
    title:
      column-name: title
    credit:
      column-name: cred
    debit:
      column-name: deb

stream:
  max-byte-threshold: 1024
  max-line-threshold: 2

