apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-service
    layer: backend
  name: product-service
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 8080
  selector:
    app: product-service
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
    layer: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: truenemec/product-service:0.0.1-SNAPSHOT
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://product-db:6001/product_db
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
          ports:
            - containerPort: 8080
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-db
    layer: database
  name: product-db
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 5432
  selector:
    app: product-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db
  labels:
    app: postgres
    layer: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
        - name: postgres
          image:  postgres:12.4
          env:
            - name: POSTGRES_DB
              value: product_db
            - name: POSTGRES_USER
              value: product_db
            - name: POSTGRES_PASSWORD
              value: product_db
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - product_db
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
              exec:
                command:
                  - pg_isready
                  - -h
                  - localhost
                  - -U
                  - product_db
              initialDelaySeconds: 5
              timeoutSeconds: 1
          ports:
            - containerPort: 5432
              protocol: TCP

