apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-chart.product-service.service.name" . }}
  labels:
    {{- include "product-chart.labels" . | nindent 4 }}
    app: product-service
spec:
  ports:
    - port: {{ .Values.product_service.service.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "product-chart.selectorLabels" . | nindent 4 }}
    app: product-service
  type: {{ .Values.product_service.service.type }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "product-chart.product-service.deployment.name" . }}
  labels:
    {{- include "product-chart.labels" . | nindent 4 }}
    app: product-service
spec:
  replicas: {{ .Values.product_service.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "product-chart.selectorLabels" . | nindent 6 }}
      app: product-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "product-chart.selectorLabels" . | nindent 8 }}
        app: product-service
    spec:
      containers:
        - name: {{ include "product-chart.product-service.container.name" . }}
          image: "{{ .Values.product_service.image.name }}:{{ .Values.product_service.image.tag }}"
          imagePullPolicy: {{ .Values.product_service.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "product-chart.urlConfig.defaultName" . }}
                  key: product_db.url
            - name: DATABASE_USER
              value: {{ .Values.product_db.db.user }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.product_db.db.password }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
          ports:
            - containerPort: 8080
              protocol: TCP
