apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "product-chart.urlConfig.defaultName" . }}
  labels:
    {{- include "product-chart.labels" . | nindent 4 }}
data:
  product_db.url: "jdbc:postgresql://{{ include "product-chart.product-db.service.name" . }}:{{ .Values.product_db.service.port }}/{{ .Values.product_db.db.dbname }}"
